import Script from 'next/script'
import { cookies } from 'next/headers'
import type { Metadata } from 'next'
import Layout from '@/components/Layout'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies()
  const fontSize = cookieStore.get('fontSize')?.value
  return (
    <html lang="en" style={{ fontSize: fontSize, opacity: fontSize === undefined ? 0 : 1 }}>
      <head>
        <Script id="analytics-script" src="flexble.js" />
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
