const themeColor = {
  transparent: 'transparent',
  title: 'rgba(var(--title) / <alpha-value>)',
  bg: 'rgb(var(--bg) / <alpha-value>)',
  reversal_bg: 'rgb(var(--reversal-bg) / <alpha-value>)',
  text: 'rgb(var(--text) / <alpha-value>)',
  primary: 'rgb(var(--primary) / <alpha-value>)',
  deep_primary: 'rgb(var(--deep-primary) / <alpha-value>)',
  secondary: 'rgb(var(--secondary) / <alpha-value>)',
  reversal_title: 'rgb(var(--reversal-title) / <alpha-value>)',
  reversal_subtitle: 'rgb(var(--reversal-subtitle) / <alpha-value>)',
  alfalfa: 'rgb(var(--alfalfa) / <alpha-value>)',
  downy: 'rgb(var(--downy) / <alpha-value>)',
  lavender_purple: 'rgb(var(--lavender-purple) / <alpha-value>)',
  intense_violet: 'rgb(var(--intense-violet) / <alpha-value>)',
  white: 'rgb(var(--white) / <alpha-value>)',
  black: 'rgb(var(--black) / <alpha-value>)',
  light_blue: 'rgb(var(--light-blue) / <alpha-value>)',
  medium_gray: 'rgb(var(--medium-gray) / <alpha-value>)',
  deep_ocean_blue: 'rgb(var(--deep-ocean-blue) / <alpha-value>)',
  neutral_grey: 'rgb(var(--neutral-grey) / <alpha-value>)',
  light_grey: 'rgb(var(--light-grey) / <alpha-value>)',
  dawn_grey: 'rgb(var(--dawn-grey) / <alpha-value>)',
  sky_lavender: 'rgb(var(--sky-lavender) / <alpha-value>)',
  mid_night_blue: 'rgb(var(--mid-night-blue) / <alpha-value>)',
  gentle_orange: 'rgb(var(--gentle-orange) / <alpha-value>)',
  sky_haze: 'rgb(var(--sky-haze) / <alpha-value>)',
  mist_white: 'rgb(var(--mist-white) / <alpha-value>)',
  ethereal_grey: 'rgb(var(--ethereal-grey) / <alpha-value>)',
  hazy_white: 'rgb(var(--hazy-white) / <alpha-value>)',
}

export default themeColor
